import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
import { Toaster } from "react-hot-toast";   // ✅ Added

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by Getnextjs Templates",
  verification: {
    google: "33xMJIYLkQJfL55d1EwYyzgMS5pHiUanGDPY5B6f0M0", // ✅ Added here
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={bricolageGrotesque.className}>
        
        {/* Header */}
        <Header />

        {/* Page Content */}
        {children}

        {/* Footer */}
        <Footer />

        {/* 🔥 Toast Notifications */}
        <Toaster position="top-right" />

      </body>
    </html>
  );
}
